version: '3.8'
services:
  typesense:
    image: typesense/typesense:26.0
    container_name: typesense
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    environment:
      - TYPESENSE_API_KEY
    command: >
      --data-dir /data
      --api-key=$${TYPESENSE_API_KEY}
      --enable-cors
    networks:
      - typesense-network

networks:
  typesense-network:
    driver: bridge
